In [ ]:
from google.colab import files
uploaded = files.upload()

Saving olist_customers_dataset.csv to olist_customers_dataset.csv
Saving olist_order_items_dataset.csv to olist_order_items_dataset.csv
Saving olist_products_dataset.csv to olist_products_dataset.csv
Saving olist_orders_dataset.csv to olist_orders_dataset.csv

In [ ]:
import pandas as pd
import sqlite3

customers = pd.read_csv('olist_customers_dataset.csv')
orders = pd.read_csv('olist_orders_dataset.csv')
order_items = pd.read_csv('olist_order_items_dataset.csv')
products = pd.read_csv('olist_products_dataset.csv')

conn = sqlite3.connect(':memory:')

customers.to_sql('customers', conn, index=False, if_exists='replace')
orders.to_sql('orders', conn, index=False, if_exists='replace')
order_items.to_sql('order_items', conn, index=False, if_exists='replace')
products.to_sql('products', conn, index=False, if_exists='replace')

print("Tables loaded successfully")

Tables loaded successfully

In [ ]:
pd.read_sql_query("SELECT * FROM orders LIMIT 5;", conn)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [4]:
query = """
SELECT
    substr(o.order_purchase_timestamp, 1, 7) AS month,
    SUM(oi.price) AS revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY month
ORDER BY month;
"""

pd.read_sql_query(query, conn)

      month     revenue
0   2016-09      267.36
1   2016-10    49507.66
2   2016-12       10.90
3   2017-01   120312.87
4   2017-02   247303.02
5   2017-03   374344.30
6   2017-04   359927.23
7   2017-05   506071.14
8   2017-06   433038.60
9   2017-07   498031.48
10  2017-08   573971.68
11  2017-09   624401.69
12  2017-10   664219.43
13  2017-11  1010271.37
14  2017-12   743914.17
15  2018-01   950030.36
16  2018-02   844178.71
17  2018-03   983213.44
18  2018-04   996647.75
19  2018-05   996517.68
20  2018-06   865124.31
21  2018-07   895507.22
22  2018-08   854686.33
23  2018-09      145.00

In [5]:
query = """
SELECT
    substr(order_purchase_timestamp, 1, 7) AS month,
    COUNT(DISTINCT order_id) AS total_orders
FROM orders
GROUP BY month
ORDER BY month;
"""

pd.read_sql_query(query, conn)

      month  total_orders
0   2016-09             4
1   2016-10           324
2   2016-12             1
3   2017-01           800
4   2017-02          1780
5   2017-03          2682
6   2017-04          2404
7   2017-05          3700
8   2017-06          3245
9   2017-07          4026
10  2017-08          4331
11  2017-09          4285
12  2017-10          4631
13  2017-11          7544
14  2017-12          5673
15  2018-01          7269
16  2018-02          6728
17  2018-03          7211
18  2018-04          6939
19  2018-05          6873
20  2018-06          6167
21  2018-07          6292
22  2018-08          6512
23  2018-09            16
24  2018-10             4

In [6]:
query = """
SELECT
    ROUND(SUM(price) * 1.0 / COUNT(DISTINCT order_id), 2) AS average_order_value
FROM order_items;
"""

pd.read_sql_query(query, conn)

   average_order_value
0               137.75

In [7]:
query = """
SELECT
    p.product_category_name,
    ROUND(SUM(oi.price), 2) AS revenue
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY p.product_category_name
ORDER BY revenue DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

    product_category_name     revenue
0            beleza_saude  1258681.34
1      relogios_presentes  1205005.68
2         cama_mesa_banho  1036988.68
3           esporte_lazer   988048.97
4  informatica_acessorios   911954.32
5        moveis_decoracao   729762.49
6              cool_stuff   635290.85
7   utilidades_domesticas   632248.66
8              automotivo   592720.11
9      ferramentas_jardim   485256.46

In [8]:
query = """
SELECT
    c.customer_unique_id,
    ROUND(SUM(oi.price), 2) AS total_spent
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_unique_id
ORDER BY total_spent DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

                 customer_unique_id  total_spent
0  0a0a92112bd4c708ca5fde585afaa872      13440.0
1  da122df9eeddfedc1dc1f5349a1a690c       7388.0
2  763c8b1c9c68a0229c42c9fc6f662b93       7160.0
3  dc4802a71eae9be1dd28f5d788ceb526       6735.0
4  459bef486812aa25204be022145caa62       6729.0
5  ff4159b92c40ebe40454e3e6a7c35ed6       6499.0
6  4007669dec559734d6f53e029e360987       5934.6
7  eebb5dda148d3893cdaf5b5ca3040ccb       4690.0
8  5d0a2980b292d049061542014e8960bf       4599.9
9  48e1ac109decbb87765a3eade6854098       4590.0

In [10]:
query = """
WITH customer_orders AS (
    SELECT
        c.customer_unique_id,
        o.order_id,
        o.order_purchase_timestamp,
        ROW_NUMBER() OVER (
            PARTITION BY c.customer_unique_id
            ORDER BY o.order_purchase_timestamp
        ) AS order_number
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
)
SELECT
    CASE
        WHEN order_number = 1 THEN 'new'
        ELSE 'returning'
    END AS customer_type,
    COUNT(*) AS total_orders
FROM customer_orders
GROUP BY customer_type;
"""

pd.read_sql_query(query, conn)

  customer_type  total_orders
0           new         96096
1     returning          3345

In [11]:
query = """
WITH customer_order_counts AS (
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS order_count
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    GROUP BY c.customer_unique_id
)
SELECT
    COUNT(CASE WHEN order_count > 1 THEN 1 END) * 100.0 / COUNT(*) AS repeat_customer_rate
FROM customer_order_counts;
"""

pd.read_sql_query(query, conn)

   repeat_customer_rate
0              3.118756

In [12]:
query = """
SELECT
    c.customer_state,
    ROUND(SUM(oi.price), 2) AS revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_state
ORDER BY revenue DESC;
"""

pd.read_sql_query(query, conn)

   customer_state     revenue
0              SP  5202955.05
1              RJ  1824092.67
2              MG  1585308.03
3              RS   750304.02
4              PR   683083.76
5              SC   520553.34
6              BA   511349.99
7              DF   302603.94
8              GO   294591.95
9              ES   275037.31
10             PE   262788.03
11             CE   227254.71
12             PA   178947.81
13             MT   156453.53
14             MA   119648.22
15             MS   116812.64
16             PB   115268.08
17             PI    86914.08
18             RN    83034.98
19             AL    80314.81
20             SE    58920.85
21             TO    49621.74
22             RO    46140.64
23             AM    22356.84
24             AC    15982.95
25             AP    13474.30
26             RR     7829.43

In [13]:
query = """
WITH monthly_revenue AS (
    SELECT
        substr(o.order_purchase_timestamp, 1, 7) AS month,
        SUM(oi.price) AS revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY month
)
SELECT
    month,
    ROUND(revenue, 2) AS revenue
FROM monthly_revenue
ORDER BY revenue DESC;
"""

pd.read_sql_query(query, conn)

      month     revenue
0   2017-11  1010271.37
1   2018-04   996647.75
2   2018-05   996517.68
3   2018-03   983213.44
4   2018-01   950030.36
5   2018-07   895507.22
6   2018-06   865124.31
7   2018-08   854686.33
8   2018-02   844178.71
9   2017-12   743914.17
10  2017-10   664219.43
11  2017-09   624401.69
12  2017-08   573971.68
13  2017-05   506071.14
14  2017-07   498031.48
15  2017-06   433038.60
16  2017-03   374344.30
17  2017-04   359927.23
18  2017-02   247303.02
19  2017-01   120312.87
20  2016-10    49507.66
21  2016-09      267.36
22  2018-09      145.00
23  2016-12       10.90